# Generated by Django 6.0.3 on 2026-03-12 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('data_cadrastro', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lojaapp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Ordem_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordenado_por', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco_envio', models.CharField(max_length=200)),
                ('subtotal', models.PositiveIntegerField()),
                ('status_pedido', models.CharField(choices=[('Pedido Recebido', 'Pedido Recebido'), ('Pedido Processado', 'Pedido Processado'), ('Pedido Caminho', 'Pedido Caminho'), ('Pedido Completado', 'Pedido Completado'), ('Pedido Cancelado', 'Pedido Cancelado')], max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('Carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojaapp.carrinho')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='produtos')),
                ('preco_mercado', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('visualizacao', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojaapp.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('subtotal', models.PositiveIntegerField(default=0)),
                ('avaliacao', models.PositiveIntegerField(default=0)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojaapp.carrinho')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojaapp.produto')),
            ],
        ),
    ]
