# Generated by Django 6.0.3 on 2026-03-12 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ordem_pedido',
            new_name='OrdemPedido',
        ),
    ]
