# Generated by Django 6.0.3 on 2026-03-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0002_rename_ordem_pedido_ordempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordempedido',
            name='desconto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordempedido',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordempedido',
            name='subtotal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
