# Generated by Django 6.0.3 on 2026-03-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0003_ordempedido_desconto_ordempedido_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordempedido',
            old_name='Carrinho',
            new_name='carrinho',
        ),
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='avaliacao',
        ),
        migrations.AlterField(
            model_name='ordempedido',
            name='status_pedido',
            field=models.CharField(choices=[('Pedido Recebido', 'Pedido Recebido'), ('Pedido Processado', 'Pedido Processado'), ('Pedido Caminho', 'Pedido Caminho'), ('Pedido Completado', 'Pedido Completado'), ('Pedido Cancelado', 'Pedido Cancelado')], default='Pedido Recebido', max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produtos'),
        ),
    ]
